version: "3"

tasks:
  build:
    cmds:
      - go build -o markout{{exeExt}} cmd/markout/main.go {{.CLI_ARGS}}
    deps:
      - generate

  generate:
    cmds:
      - go generate ./...

  test:
    cmds:
      - go test -v ./...
    deps:
      - generate

  lint:
    cmds:
      - gofmt -l .
      - go vet ./...

  clean:
    cmds:
      - go clean -cache
      - go run internal/cmd/clean/main.go

  tidy:
    cmds:
      - go mod tidy
      # add preprocessor dependencies used by generate but ignored by build
      - go get github.com/tdewolff/minify/v2

  run:
    desc: Run the application to print all relative inputs to stdout
    cmds:
      - task build
      - ./markout{{exeExt}} {{.CLI_ARGS}}

  example:
    desc: Run an example to stdout
    cmds:
      - ./markout{{exeExt}} ./examples/example.md -o

  default:
    cmds:
      - task clean
      - task tidy
      - task generate
      - task lint
      - task test
      - task build
