version: '3'

tasks:
  build:
    cmds:
      - go build -o markout{{exeExt}} cmd/markout/main.go

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - gofmt -l .
      - go vet ./...

  clean:
    cmds:
      - go clean -cache
  
  tidy:
    cmds:
      - go mod tidy
  
  run:
    desc: Run the application to print all relative inputs to stdout
    cmds:
      - ./markout{{exeExt}} -o

  example:
    desc: Run the application to generate outputs in directory
    cmds:
      - ./markout{{exeExt}} example.md -d ./markoutput

  all: # Define the default task
    cmds:
      - task lint
      - task test
      - task build
